<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:tns="DeptEmpAPI_getEmployeeDetails_response"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/getEmployeeDetails"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/HRM_REST_API/HRM_REST_API/getEmployeeDetails"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns2="http://xmlns.oracle.com/HRM_REST_API/HRM_REST_API/DeptEmpAPI2">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/getEmployeeDetails.wsdl"/>
                <oracle-xsl-mapper:rootElement name="OutputParameters"
                                               namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/getEmployeeDetails"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/DeptEmpAPI2.wsdl"/>
                <oracle-xsl-mapper:rootElement name="EmployeeRoot" namespace="DeptEmpAPI_getEmployeeDetails_response"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON SEP 18 08:41:33 CEST 2017].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <tns:EmployeeRoot>
            <tns:name>
                <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:NAME"/>
            </tns:name>
            <tns:id>
                <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:ID"/>
            </tns:id>
            <tns:job>
                <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:JOB"/>
            </tns:job>
            <tns:hiredate>
                <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:HIREDATE"/>
            </tns:hiredate>
            <tns:salary>
                <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:SALARY"/>
            </tns:salary>
            <tns:commission>
                <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:COMMISSION"/>
            </tns:commission>
            <tns:departmentId/>
            <tns:managerId>
                <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:MANAGER/ns0:ID"/>
            </tns:managerId>
            <tns:departmentName>
                <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:DEPARTMENT_NAME"/>
            </tns:departmentName>
            <tns:departmentLocation>
                <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:DEPARTMENT_LOCATION"/>
            </tns:departmentLocation>
            <tns:managerName>
                <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:MANAGER/ns0:NAME"/>
            </tns:managerName>
            <tns:managerJob>
                <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:MANAGER/ns0:JOB"/>
            </tns:managerJob>
            <xsl:for-each select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:STAFF/ns0:STAFF_ITEM">
                <tns:staff>
                    <tns:id>
                        <xsl:value-of select="ns0:ID"/>
                    </tns:id>
                    <tns:name>
                        <xsl:value-of select="ns0:NAME"/>
                    </tns:name>
                    <tns:job>
                        <xsl:value-of select="ns0:JOB"/>
                    </tns:job>
                </tns:staff>
            </xsl:for-each>
        </tns:EmployeeRoot>
    </xsl:template>
</xsl:stylesheet>
