<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="RestEMPService_getEmployeeDetails_response"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/getEmployeeDetails"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/HRM_REST_API/HRM_REST_API/getEmployeeDetails"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:inp12="EMPRestService_getEmployees_response"
                xmlns:inp5="HrmRestAPI_GetDepartmentDetails_response" xmlns:inp4="HrmRestAPI_Result_response"
                xmlns:inp13="EMPRestService_createEmployee_request"
                xmlns:ns2="http://xmlns.oracle.com/HRM_REST_API/HRM_REST_API/HRMRestAPI"
                xmlns:inp2="HrmRestAPI_getAllDepartments_response" xmlns:inp3="HrmRestAPI_CreateDepartments_request"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/getEmployeeDetails.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OutputParameters"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/getEmployeeDetails"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/HRMRestAPI.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Employee" namespace="RestEMPService_getEmployeeDetails_response"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SUN SEP 17 18:44:28 CEST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:Employee>
      <tns:name>
        <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:NAME"/>
      </tns:name>
      <tns:id>
        <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:ID"/>
      </tns:id>
      <tns:job>
        <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:JOB"/>
      </tns:job>
      <tns:hiredate>
        <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:HIREDATE"/>
      </tns:hiredate>
      <tns:salary>
        <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:SALARY"/>
      </tns:salary>
      <tns:commission>
        <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:COMMISSION"/>
      </tns:commission>
      <tns:departmentId>
        <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:DEPARTMENT_ID"/>
      </tns:departmentId>
      <tns:managerId>
        <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:MANAGER/ns0:ID"/>
      </tns:managerId>
      <tns:departmentName>
        <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:DEPARTMENT_NAME"/>
      </tns:departmentName>
      <tns:departmentLocation>
        <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:DEPARTMENT_LOCATION"/>
      </tns:departmentLocation>
      <tns:managerName>
        <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:MANAGER/ns0:NAME"/>
      </tns:managerName>
      <tns:managerJob>
        <xsl:value-of select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:MANAGER/ns0:JOB"/>
      </tns:managerJob>
      <xsl:for-each select="/ns0:OutputParameters/ns0:GET_EMPLOYEE/ns0:STAFF/ns0:STAFF_ITEM">
        <tns:staff>
          <tns:id>
            <xsl:value-of select="ns0:ID"/>
          </tns:id>
          <tns:name>
            <xsl:value-of select="ns0:NAME"/>
          </tns:name>
          <tns:job>
            <xsl:value-of select="ns0:JOB"/>
          </tns:job>
        </tns:staff>
      </xsl:for-each>
    </tns:Employee>
  </xsl:template>
</xsl:stylesheet>
